# Load Data

In [1]:
import pandas as pd
import ast

In [2]:
def row_str_to_list(row):
    row['outreview'] = ' '.join(ast.literal_eval(row['outreview']))
    row['outtitle'] = ' '.join(ast.literal_eval(row['outtitle']))
    return row

In [3]:
data=pd.read_csv('data/multi/train.csv')
data = data.apply(row_str_to_list, axis=1)

In [4]:
data

,outtitle,outreview,label
0,wonderful dress,love dress think cut fabric embroidery flatter...,2
1,no brainer,dress truly no brainer purchase stunning dress...,2
2,nice tank,like look tank ran bit larger expected neck bu...,2
3,love,perfect end summer going fall soft pairs great...,2
4,vintage vibe builtin support,good dress hourglass figures runs bit narrow r...,2
5,cute comfy,really love soft nice quality complaint straps...,2
6,disappointed retailers descriptions lately,one proved no different short end dress pretty...,0
7,beautiful dress,beautiful dress delicately well made 51 95lb x...,2
8,swinging dress,thought dress store true size bit more swingin...,2
9,gorgeous dress,worse dress rehersal dinner received many comp...,2
10,surprise winner,tried store size but thought felt tight but pe...,2
11,love top,picture wasnt sure would fit got mail love fit...,2
12,curvy girls beware,dress beautiful color fabric super soft lovely...,1
13,new summer go,jumper cute soft dress depending going,2
14,perfect skirt,love colors skirt wear tee flat sandals black ...,2
15,gotten multiple compliments,dont usually wear much color but im glad purch...,2
16,darker person,got skirt mail today overall im happy keep dis...,2
17,great basic tee,got color listed pink not usual pink fit goodn...,2
18,fancy sweatshirt,beautiful long midi blazer happens feel like s...,2
19,love romper,first romper purchased cute small medium usual...,2
20,love texture color,love texture color tunic seem run large could ...,2
21,nice top,like reviewers experienced received top mail n...,2
22,disappointing,expecting tunic bit structure weight layer leg...,1
23,soft warm,like contrast skirt bodice length sleeves adn ...,2
24,gorgeous,most beautiful top closet huge closet beautifu...,2
25,love,im pregnant 2nd trimester really wanted beauti...,2
26,really nice top,really love top great colors comfortable long ...,2
27,beautiful dress,actually bought dress last year made another o...,2
28,stays put,classic design nice details stays place active...,2
29,love but pink blue not cream blue,heads didnt notice pink blue motif print arriv...,2
...,...,...,...
15710,le sac,struggling find nice flowy summer dress isnt t...,0
15711,alter waist,53 2838 ordered regular left way came would lo...,2
15712,cute dont size,cute shirt thought model would big sized more ...,2
15713,ugg,skirt gianormous usually take xl l ordered wai...,0
15714,buy one size,love shirt bought shirt returning shirt believ...,2
15715,not,obsessed dress moment saw online excited buy c...,1
15716,dressed,looked reviews purchasing one time didnt work ...,2
15717,beautiful detail loose fit,loved fabric details cut tad looserbigger expe...,1
15718,missed mark,online dress looks perfect but person bit dowd...,1
15719,great shape,loved shape basic jacket perfect go yoga dress...,2
15720,gorgeous embroidery,purchased dress regular size small soon saw po...,2
15721,pretty alterations whiz,gorgeous sleeves flattering necklineand volumi...,1
15722,cute dress,got wear beach vacation later august hesitant ...,2
15723,cute details good cut,im sucker lace details dress otherwise plain w...,2
15724,amazing,fell love jumpsuit first sight color stunning ...,2
15725,perfect red cardi,wish list but saw black fridayand happened sis...,2
15726,truly unflattering,granted not reed thin young model but tall rea...,0
15727,love,shirt great person online substantial fabric n...,2
15728,well made,jacket looks great well made material lush how...,1
15729,looks nothing like photo,poorly made wide short unflattering material a...,0
15730,gorgeous white summer tank,got white surprised see fits petite but 32d bu...,2
15731,even better pictured,shirt beautiful fits perfectly soft too didnt ...,2
15732,unexpected color fantastic coat,bought 20 off sale made even more worth price ...,2
15733,super cute wee bit small,im loving even wee bit tight im 56 130 lbs hit...,2
15734,pretty but not good enough full price,thought dress lovely im 810 tried med believe ...,2
15735,love,love dress color quality design great sizing t...,2
15736,beautiful skirt,agree reviewer skirt beautiful print combed co...,2
15737,comfy classic,love sweater wish sized little longer length b...,2
15738,comfy,comfy dresstunic like wear leggings washed wel...,2
15739,runs big short,dress shorter looks model im 58 hits 1 inch kn...,2

# Compute Frequency

리뷰의 유형(긍정, 부정, 중립) 및 제목과 본문 간의 빈도 상위 단어 차이를 분석합니다.

In [5]:
matrixdata=data.as_matrix()

In [6]:
pos_title=[]
pos_review=[]
neg_title=[]
neg_review=[]
neu_title=[]
neu_review=[]
for i in matrixdata:
    title = i[0]
    review = i[1]
    label = i[2]
    
    if label == 2:
        pos_title.extend(title.split())
        pos_review.extend(review.split())
    elif label == 1:
        neu_title.extend(title.split())
        neu_review.extend(review.split())
    else:
        neg_title.extend(title.split())
        neg_review.extend(review.split())

In [7]:
import nltk

In [8]:
post=nltk.FreqDist(i for i in pos_title)
posr=nltk.FreqDist(i for i in pos_review)
negt=nltk.FreqDist(i for i in neg_title)
negr=nltk.FreqDist(i for i in neg_review)
neut=nltk.FreqDist(i for i in neu_title)
neur=nltk.FreqDist(i for i in neu_review)

In [31]:
def freqdist_to_table(freqdist):
    df = pd.DataFrame.from_dict(freqdist, orient='index')
    df.columns = ['frequency']
    return df.sort_values('frequency', ascending=False)[:10]

## 전체 상위 빈도 단어

In [35]:
total = post + posr + negt + negr + neut + neur
freqdist_to_table(total)

       frequency
but        12883
dress       8768
not         7698
love        7598
size        6429
top         6060
fit         5666
great       5599
like        5242
too         4703

## 리뷰 유형별 상위 빈도 단어 비교

In [9]:
pos = post + posr
neg = negt + negr
neu = neut + neur

In [32]:
freqdist_to_table(pos)

       frequency
but         9029
dress       6800
love        6622
size        5175
great       4976
not         4929
top         4561
fit         4219
wear        3872
like        3571

In [33]:
freqdist_to_table(neg)

        frequency
but          1516
not          1256
dress         860
like          802
too           656
top           617
fit           586
fabric        548
would         512
size          504

In [34]:
freqdist_to_table(neu)

        frequency
but          2338
not          1513
dress        1108
too           999
top           882
like          869
fit           861
size          750
would         673
fabric        663

## 제목 / 리뷰 별 상위 빈도 단어 비교

In [36]:
title = post + negt + neut
review = posr + negr + neur

In [37]:
freqdist_to_table(title)

           frequency
love            1473
great           1417
dress           1331
but             1234
cute            1226
beautiful       1102
top              914
not              817
perfect          644
pretty           532

In [38]:
freqdist_to_table(review)

       frequency
but        11649
dress       7437
not         6881
size        6268
love        6125
fit         5184
top         5146
like        5041
wear        4526
too         4320